kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: H3LMifHDe3jNaFlkn9JDhbr11wdHFpmTScFpqga5XqQ=
      - identity: {}
